**Septa Inda_09011181823126_UAS Kecerdasan Buatan**

**Bank Customers Analysis With Artificial Neural Netowrk**


  * **Part 1 - Data Preprocessing**   
  * Importing libraries
  * Importing the dataset
  * Dataset information (Pandas Profiling)    
  * Spliting the Train & Test datasets
  * Feature Scaling
* **Part 2 - Building the ANN**    
  * Initializing the ANN    
  * Adding the input layer and the first hidden layer    
  * Adding the second hidden layer    
  * Adding the output layer    
* **Part 3 - Training the ANN**    
  * Compiling the ANN
  * Training the ANN on the Training set   
* **Part 4 - Making the predictions and evaluating the model**    
  * Predicting the Test set results    
  * Making the Confusion Matrix    















**Importing the libraries**

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

**Part 1 - Data Preprocessing**


**Importing the dataset**

In [4]:
dataset = pd.read_csv('./Bank_Customers_Analysis_By_ANN.csv')
X = dataset.iloc[:, 7:-1].values
y = dataset.iloc[:, -1].values

dataset terdiri dari 14 data informasi nasabah bank yaitu : RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited

Pada variabel X data yang digunakan pada dataset adalah data ketujuh berdasarkan index 
sampai data ke 2 dari terakhir dan variabel y menggunakan data pada index terakhir dataset

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [6]:
X

array([[2.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [1.0000000e+00, 8.3807860e+04, 1.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [8.0000000e+00, 1.5966080e+05, 3.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [3.0000000e+00, 7.5075310e+04, 2.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [4.0000000e+00, 1.3014279e+05, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [9]:
y

array([1, 0, 1, ..., 1, 1, 0])

**Dataset information (Pandas Profiling)¶**

In [10]:
import pandas_profiling as pp
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

**Splitting the dataset into the Training set and Test set**

Training set adalah bagian dataset yang kita latih untuk membuat prediksi atau menjalankan fungsi dari sebuah algoritma ML. Kita memberikan petunjuk melalui algoritma agar mesin yang kita latih bisa mencari korelasinya sendiri atau belajar pola dari data yang diberikan.
Test set adalah bagian dataset yang kita tes untuk melihat keakuratannya, atau dengan kata lain melihat performanya.

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Proses pendefinisian X_train sebagai data X yang ingin kita latih (train), X_test sebagai data X yang ingin kita tes, y_train adalah variabel dependen yang dilatih, dan y_test merupakan variabel dependen yang diuji dengan menggunakan Parameter test_size sebesar 0,2 yang Biasanya digunakan sebagai rule of thumb (aturan umum) proporsi test set sebesar 0,2 dan train set 0,8. Parameter lainnya adalah random_state yang merupakan random number generator (RNG) yang kali ini kita pilih adalah angka nol.

**Feature Scaling**

Feature Scaling adalah suatu cara untuk membuat numerical data pada dataset memiliki rentang nilai (scale) yang sama

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Part 2 - Building the ANN**

**Initializing the ANN**

In [13]:
ann = tf.keras.models.Sequential()

**Adding the input layer and the first hidden layer**

In [14]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

Berikutnya adalah proses dense. Dense adalah fungsi untuk menambahkan layer yang fully connected.
units menandakan jumlah node yang harus ada di hidden layer, nilainya antara jumlah input node dan output node. Sedangkan fungsi aktivasinya kita gunakan relu.

**Adding the second hidden layer**

In [15]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

**Adding the output layer**

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Inisialisasis layer output, yang hanya berupa satu node karena klasifikasi ini termasuk dalam binary classification.

**Part 3 - Training the ANN**

**Compiling the ANN**

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

untuk tahap kompilasi nya, parameter optimisasi menggunakan adam optimizer untuk menentukan algoritma stochastic gradient descent, parameter loss menggunakan binary crossentropy untuk menentukan loss function dan parameter metrics untuk menentukan performa metric

**Training the ANN on the Training set**

Kemudian dilakukan training dengan iterasi epoch sebesar 80

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 80)

Epoch 1/80
250/250 [==============================] - 0s 905us/step - loss: 0.6365 - accuracy: 0.6481
Epoch 2/80
250/250 [==============================] - 0s 874us/step - loss: 0.4982 - accuracy: 0.7960
Epoch 3/80
250/250 [==============================] - 0s 925us/step - loss: 0.4851 - accuracy: 0.7960
Epoch 4/80
250/250 [==============================] - 0s 995us/step - loss: 0.4782 - accuracy: 0.7960
Epoch 5/80
250/250 [==============================] - 0s 917us/step - loss: 0.4732 - accuracy: 0.7960
Epoch 6/80
250/250 [==============================] - 0s 871us/step - loss: 0.4689 - accuracy: 0.7960
Epoch 7/80
250/250 [==============================] - 0s 896us/step - loss: 0.4646 - accuracy: 0.7960
Epoch 8/80
250/250 [==============================] - 0s 871us/step - loss: 0.4605 - accuracy: 0.7961
Epoch 9/80
250/250 [==============================] - 0s 926us/step - loss: 0.4567 - accuracy: 0.7960
Epoch 10/80
250/250 [==============================] - 0s 871us/step - loss: 0.452

**Part 4 - Making the predictions and evaluating the model**

**Predicting the Test set results**

pada tahap ini dilakukanlah prediksi pada dataset (X_test), y_pred menunujukkan bahwa setiap barisnya memiliki probabilitas
Karena kita sebelumnya menggunakan fungsi sigmoid saat menggunakan activation function. arena yang Yang kita butuhkan bukanlah probabilitas, namun dua nilai antara 0 dan 1, maka kita konversi nilai probabilitas ini. Nilai probabilitas > 0.5 akan bernilai 1 (True), dan sebaliknya bernilai 0 (False).

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


**Making the Confusion Matrix**

Confusion matrix digunakan untuk mengukur  kinerja dari model klasifikasi yang digunakan. Dalam hal ini kita menggunakan akurasi sebagai tolak ukur

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred)*100))

[[1561   34]
 [ 325   80]]
Accuracy: 82.05%
